name: gw_fix
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - astropy=6.1.7
  - astropy-base=6.1.7
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-http=0.10.13
  - aws-c-io=0.26.3
  - aws-c-s3=0.12.2
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - backports.zstd=1.4.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.14.3
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.5.20
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2026.5.20
  - cffi=2.0.0
  - cfitsio=4.4.1
  - charset-normalizer=3.4.7
  - click=8.3.3
  - contourpy=1.3.2
  - cpython=3.10.20
  - cryptography=48.0.0
  - cycler=0.12.1
  - cython=3.2.4
  - dateparser=1.4.0
  - decorator=5.2.1
  - dqsegdb2=1.3.0
  - fftw=3.3.11
  - fonttools=4.62.1
  - freetype=2.14.3
  - future=1.0.0
  - gmp=6.3.0
  - gmpy2=2.3.0
  - gsl=2.7
  - gwdatafind=2.1.1
  - gwosc=0.8.2
  - gwpy=3.0.14
  - h2=4.3.0
  - h5py=3.16.0
  - hdf5=2.1.0
  - healpy=1.18.0
  - hpack=4.1.0
  - htgettoken=2.6
  - hyperframe=6.1.0
  - icu=78.3
  - idna=3.13
  - igwn-auth-utils=1.4.0
  - igwn-segments=2.1.1
  - importlib-metadata=8.8.0
  - invoke=3.0.3
  - jinja2=3.1.6
  - jplephem=2.24
  - jq=1.8.1
  - keyutils=1.6.3
  - kiwisolver=1.5.0
  - krb5=1.22.2
  - lal=7.7.0
  - lalapps=10.0.2
  - lalburst=2.0.6
  - lalframe=3.0.7
  - lalinference=4.1.7
  - lalinference-data=4.1.7
  - lalinspiral=5.0.2
  - lalmetaio=4.0.6
  - lalpulsar=7.1.0
  - lalpulsar-data=7.1.0
  - lalsimulation=6.2.0
  - lalsimulation-data=6.2.0
  - lcms2=2.19
  - ld_impl_linux-64=2.45.1
  - ldas-tools-al=2.7.0
  - ldas-tools-framecpp=2.9.3
  - lerc=4.1.0
  - libaec=1.1.5
  - libblas=3.11.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.20.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.5
  - libffi=3.5.2
  - libframel=8.48.5
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libjpeg-turbo=3.1.4.1
  - liblal=7.7.0
  - liblalburst=2.0.6
  - liblalframe=3.0.7
  - liblalinference=4.1.7
  - liblalinspiral=5.0.2
  - liblalmetaio=4.0.6
  - liblalpulsar=7.1.0
  - liblalsimulation=6.2.0
  - liblapack=3.11.0
  - liblzma=5.8.3
  - libmetaio=8.5.1
  - libnghttp2=1.68.1
  - libnsl=2.0.1
  - libopenblas=0.3.32
  - libpng=1.6.58
  - libsodium=1.0.21
  - libsqlite=3.53.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.42
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.2
  - ligo-gracedb=2.15.7
  - ligo-segments=1.4.0
  - ligotimegps=2.0.1
  - lscsoft-glue=4.1.1
  - mako=1.3.12
  - markupsafe=3.0.3
  - matplotlib-base=3.10.9
  - mpc=1.4.0
  - mpfr=4.2.2
  - mpld3=0.5.12
  - mpmath=1.4.1
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.2.6
  - oniguruma=6.9.10
  - openjpeg=2.5.4
  - openssl=3.6.2
  - packaging=26.2
  - paramiko=4.0.0
  - pcre2=10.47
  - pegasus-wms.api=5.1.2
  - pegasus-wms.common=5.1.2
  - pillow=12.2.0
  - pip=26.0.1
  - pkg-config=0.29.2
  - pthread-stubs=0.4
  - pycbc=2.9.0
  - pycparser=2.22
  - pyerfa=2.0.1.5
  - pyjwt=2.12.1
  - pykerr=0.2.0
  - pynacl=1.6.2
  - pyparsing=3.3.2
  - pysocks=1.7.1
  - python=3.10.20
  - python-dateutil=2.9.0.post0
  - python-gssapi=1.11.1
  - python-lal=7.7.0
  - python-lalburst=2.0.6
  - python-lalframe=3.0.7
  - python-lalinference=4.1.7
  - python-lalinspiral=5.0.2
  - python-lalmetaio=4.0.6
  - python-lalpulsar=7.1.0
  - python-lalsimulation=6.2.0
  - python-ldas-tools-al=2.6.11
  - python-ldas-tools-framecpp=2.6.14
  - python-ligo-lw=1.8.3
  - python_abi=3.10
  - pyyaml=6.0.3
  - qhull=2020.2
  - readline=8.3
  - regex=2026.4.4
  - requests=2.33.1
  - s2n=1.7.2
  - safe-netrc=1.0.1
  - scitokens=1.9.7
  - setuptools=82.0.1
  - six=1.17.0
  - soupsieve=2.8.3
  - swig=4.4.1
  - sympy=1.14.0
  - tenacity=9.1.4
  - tk=8.6.13
  - tqdm=4.67.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzlocal=5.3.1
  - unicodedata2=17.0.1
  - urllib3=2.6.3
  - wheel=0.47.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zipp=3.23.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - astropy-iers-data==0.2026.4.27.1.3.2
      - attrs==26.1.0
      - corner==2.2.3
      - dill==0.4.1
      - igwn-ligolw==2.1.1
      - lalsuite==7.26.13
      - multiprocess==0.70.19
      - pandas==2.3.3
      - pathos==0.3.5
      - pox==0.3.7
      - ppft==1.7.8
      - ptemcee==1.0.0
      - pyfstat==2.3.0+47.54e59c73.clean
      - pytz==2026.1.post1
      - scipy==1.15.3
      - solar-system-ephemerides==1.2.0
      - superrad==0.3.0
      - tzdata==2026.2

